spring:
  datasource:
    url: jdbc:h2:mem:dockersim;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop   # 테스트 격리
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  sql:
    init:
      mode: never             # 스키마/데이터 스크립트가 필요하면 적절히 변경

logging:
  level:
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN
